# Generated by Django 4.2.7 on 2025-01-08 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0032_submission_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="token",
            field=models.TextField(default=uuid.uuid4, null=True),
        ),
    ]
