# Generated by Django 4.2.7 on 2025-01-08 13:14

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    TestResult = apps.get_model("runner", "TestResult")
    for row in TestResult.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=["token"])


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0033_testresult_token"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
