# Generated by Django 4.2.7 on 2025-01-08 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0034_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="token",
            field=models.TextField(default=uuid.uuid4, unique=True),
        )
    ]
