services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_DEV=true
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM_NAME=master
      - REACT_APP_KEYCLOAK_CLIENT_ID=arbitre
    depends_on:
      - backend
    networks:
      - keycloak_network

  backend:
    build: ./backend
    environment:
      - DEBUG=True
      - HOSTNAME=localhost
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=arbitre
      - DB_USER=arbitre
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      # - DB_HOST=postgresql://arbitre:${DB_PASSWORD}@db/arbitre
      - DB_PORT=5432
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM_NAME=master
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - OIDC_RP_CLIENT_ID=arbitre
      - API_KEY=${BACKEND_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - keycloak
    networks:
      - keycloak_network
      - db_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=arbitre
      - POSTGRES_USER=arbitre
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  kc-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kc-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - kc-db
    networks:
      - keycloak_network

  redis:
    image: redis:6

  # celery_worker:
  #   build: ./backend
  #   command: celery -A arbitre worker -l info
  #   environment:
  #     - HOSTNAME=localhost
  #     - KEYCLOAK_URL=http://keycloak:8080
  #   depends_on:
  #     - backend
  #     - redis
  #     - keycloak

  # celery_beat:
  #   build: ./backend
  #   command: celery -A arbitre beat -l info
  #   environment:
  #     - HOSTNAME=localhost
  #     - KEYCLOAK_URL=http://keycloak:8080
  #   depends_on:
  #     - backend
  #     - redis
  #     - keycloak

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - keycloak
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local
  keycloak_postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
  db_network:
    driver: bridge
