# TODO fix playbook
- name: Camisole VM
  hosts: group
  become: true
  tasks:
  - name: Ping hosts
    ansible.builtin.ping:
  - name: Install VirtualBox
    ansible.builtin.apt:
      name: virtualbox
      state: present
      update_cache: true

  - name: Create Camisole Directory
    ansible.builtin.file:
      path: ~/camisole
      state: directory
      mode: 0755
  - name: Get existing files
    ansible.builtin.find:
      paths: ~/camisole
      patterns: "camisole-latest.ova"
    register: appliance_files
  - name: Download Camisole VM Appliance
    when: '(appliance_files.files | length == 0) or "camisole" not in appliance_files.files[0].path'
    ansible.builtin.get_url:
      url: https://camisole.prologin.org/ova/camisole-latest.ova
      dest: ~/camisole
      mode: 0755

  - name: Get existing VMs
    ansible.builtin.shell:
      vboxmanage list vms
    register: list_vms
    changed_when: false
  - name: Import Camisole appliance
    when: '"camisole" not in list_vms.stdout'
    ansible.builtin.shell:
      vboxmanage import ~/camisole/camisole-latest.ova --vsys 0 --vmname camisole

  - name: Get running VMs
    ansible.builtin.shell:
      vboxmanage list runningvms
    register: list_running
    changed_when: false
  - name: Start Camisole
    when: '"camisole" not in list_running.stdout'
    ansible.builtin.shell:
      vboxmanage startvm camisole --type headless

  - name: Run test command
    ansible.builtin.uri:
      url: http://localhost:42920/
