name: Django CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:

    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: arbitre
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_HOSTNAME: "localhost"
        envkey_SECRET_KEY: "django-insecure-9p0it%1(1)sv%+s&bv0n@8330j*_)qm76ejwrzg(nea-m=v278"
        envkey_DB_NAME: arbitre-test
        envkey_DB_USER: test
        envkey_DB_PASSWORD: test
        envkey_DB_HOST: localhost
        envkey_DB_PORT: ''
        directory: '/backend/arbitre'

    - name: Run tests in nix development environment
      run: |
        nix develop --command bash -c "cd backend && coverage run manage.py test && coverage report"