name: Django CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:

    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: arbitre
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Run tests in nix development environment
      run: |
        nix develop --command bash -c "cd backend && coverage run manage.py test && coverage report"