name: Playwright Tests
on:
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Django dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Install Node dependencies
      run: | 
        npm install
      working-directory: frontend

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: frontend

    # - name: Run Django server in background
    #   env:
    #     DJANGO_ALLOW_ASYNC_UNSAFE: 1
    #   run: python manage.py runserver &
    #   working-directory: backend

    - name: Run Django and Run Playwright tests
      run: |
        cd backend
        python manage.py makemigrations >/dev/null
        python manage.py migrate >/dev/null
        python manage.py runserver &
        cd ../frontend
        npx playwright test

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
